title: 'DaoCloud 文档'
author:
  name: DaoCloud
  email: info@daocloud.io
taxonomies:
  - category
  - tag
metadata:
  description: 'DaoCloud 文档'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects:
  /hosting/rochen: /hosting/shared/rochen
  /hosting/wirenine: /hosting/shared/wirenine
  /hosting/crucial: /hosting/shared/crucial
  /hosting/arvixe: /hosting/shared/arvixe
  /hosting/siteground: /hosting/shared/siteground
  /hosting/dreamhost: /hosting/shared/dreamhost
routes:
  /something/else: /blog/sample-3
  '/new/(.*)': /blog/$1
blog:
  route: /blog
